export const GET_ALL_FURNITURES = 'GET_ALL_FURNITURES';
export const GET_FURNITURES_BY_NAME = 'GET_FURNITURES_BY_NAME';
export const FURNITURES_SORT_BY_NAME = 'FURNITURES_ SORT_BY_NAME';
export const SORT_BY_PRICE = 'SORT_BY_NAME';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const PREV = 'PREV';
export const NEXT = 'NEXT';
export const GO_TO_FIRST_PAGE = ' GO_TO_FIRST_PAGE';
export const GO_TO_LAST_PAGE = 'GO_TO_LAST_PAGE';
export const CREAR_ORDEN = 'CREAR_ORDEN';
export const  CREATE_EMAIL='CREATE_EMAIL'
export const LOGIN_GET_USER = "LOGIN_GET_USER";
export const LOGOUT = "LOGOUT";
